### PR TITLE
Cassandra Alerts

### PR DESCRIPTION
**Pull request by viivek46**
Adds prometheus-alert-rules for Cassandra.

JIRA Issue: https://jira.mesosphere.com/browse/DCOS-52832

### CODE REVIEW

**Review by philipnrmn — CHANGES_REQUESTED** [review]
Hi @viivek46 , thanks for the PR.

The alerts themselves look good to me. Can you use the severity levels specified here instead of `informational` / `major`: https://github.com/dcos/prometheus-alert-rules#severity-levels

**Comment by viivek46** [comment]
@philipnrmn updated as suggested

**Comment by philipnrmn** [comment]
@viivek46 my apologies, our docs did not make this clear (and I have fixed them now). Our convention is to use lowercase as in `warning` and `critical` - we can't have mixed case. Once this is done I will happily merge!

**Comment by viivek46** [comment]
@philipnrmn No Problem, I have done changes as requested.

**Review by philipnrmn — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
